/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomerPicker: typeof import('./src/components/CustomerPicker.vue')['default']
    InvoiceTable: typeof import('./src/components/InvoiceTable.vue')['default']
    InvoiceTableFilters: typeof import('./src/components/InvoiceTableFilters.vue')['default']
    InvoiceTableWithCustomFooter: typeof import('./src/components/InvoiceTableWithCustomFooter.vue')['default']
    InvoiceTableWithExternalPagination: typeof import('./src/components/InvoiceTableWithExternalPagination.vue')['default']
    InvoiceTambleFilters: typeof import('./src/components/InvoiceTableFilters.vue')['default']
    LazyCustomerChip: typeof import('./src/components/LazyCustomerChip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
