/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Option1': RouteRecordInfo<'/Option1', '/Option1', Record<never, never>, Record<never, never>>,
    '/Option2': RouteRecordInfo<'/Option2', '/Option2', Record<never, never>, Record<never, never>>,
    '/Option3': RouteRecordInfo<'/Option3', '/Option3', Record<never, never>, Record<never, never>>,
    '/Option4': RouteRecordInfo<'/Option4', '/Option4', Record<never, never>, Record<never, never>>,
    '/Option5': RouteRecordInfo<'/Option5', '/Option5', Record<never, never>, Record<never, never>>,
    '/Option6': RouteRecordInfo<'/Option6', '/Option6', Record<never, never>, Record<never, never>>,
  }
}
